# Generated by Django 5.1.8 on 2026-07-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/')),
                ('plant_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_healthy', models.BooleanField(default=True)),
                ('is_plant', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('kindwise', 'Kindwise API'), ('local_model', 'Local MobileNetV2 Model')], default='kindwise', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('result_data', models.JSONField(default=dict)),
                ('unsupported_crop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
