# Generated by Django 5.1.8 on 2026-07-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fertilizerrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('water_requirement', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'irrigation_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
