# Generated by Django 5.1.8 on 2026-07-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_irrigationrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, default='', max_length=100)),
                ('market', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('min_price', models.FloatField(default=0.0)),
                ('max_price', models.FloatField(default=0.0)),
                ('modal_price', models.FloatField(default=0.0)),
                ('price_date', models.DateField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_prices',
                'ordering': ['-price_date', '-fetched_at'],
                'indexes': [models.Index(fields=['commodity'], name='market_pric_commodi_283882_idx'), models.Index(fields=['state'], name='market_pric_state_125821_idx'), models.Index(fields=['price_date'], name='market_pric_price_d_665d8e_idx')],
            },
        ),
    ]
